// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdck-AgVshlszn9QKphv5VE4xXmlqpq3I',
    appId: '1:537669474731:web:09c6eaf619910d237b9aee',
    messagingSenderId: '537669474731',
    projectId: 'checkml',
    authDomain: 'checkml.firebaseapp.com',
    storageBucket: 'checkml.appspot.com',
    measurementId: 'G-BY44323C2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGxjxvjQHb0UgvewzmukavL9Md1aOv1M',
    appId: '1:537669474731:android:27fbbded6b36290c7b9aee',
    messagingSenderId: '537669474731',
    projectId: 'checkml',
    storageBucket: 'checkml.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnVVLp5Co7pdtyFa8bookpxzOgtU_3t7M',
    appId: '1:537669474731:ios:931af7ac5b2af4f97b9aee',
    messagingSenderId: '537669474731',
    projectId: 'checkml',
    storageBucket: 'checkml.appspot.com',
    iosClientId: '537669474731-q2c90q7ogb8b4o8odhuuirvcil9qrq9h.apps.googleusercontent.com',
    iosBundleId: 'com.lightphoenix.firapplicationdigtitalcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnVVLp5Co7pdtyFa8bookpxzOgtU_3t7M',
    appId: '1:537669474731:ios:931af7ac5b2af4f97b9aee',
    messagingSenderId: '537669474731',
    projectId: 'checkml',
    storageBucket: 'checkml.appspot.com',
    iosClientId: '537669474731-q2c90q7ogb8b4o8odhuuirvcil9qrq9h.apps.googleusercontent.com',
    iosBundleId: 'com.lightphoenix.firapplicationdigtitalcampus',
  );
}
